FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/cryptographic-hashing-engine-0.0.1-SNAPSHOT-standalone.jar /cryptographic-hashing-engine/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/cryptographic-hashing-engine/app.jar"]
