FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/service-orchestrator-0.0.1-SNAPSHOT-standalone.jar /service-orchestrator/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/service-orchestrator/app.jar"]
