FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/base-receiver-service-0.0.1-SNAPSHOT-standalone.jar /base-receiver-service/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/base-receiver-service/app.jar"]
