FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/rssp-google-research-paper-publication-0.0.1-SNAPSHOT-standalone.jar /rssp-google-research-paper-publication/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/rssp-google-research-paper-publication/app.jar"]
